server:
    port: 9090
spring:
    datasource:
        password: nephatmuchiri
        url: jdbc:postgresql://localhost:5432/fun_with_flags
        username: nephatmuchiri
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
