server:
    port: 9090
spring:
    datasource:
        password: Br00k51d3
        url: jdbc:mysql://localhost:3306/fun_with_flags
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
